//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=Builder.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Builder class use like Directore of Project.
    /// </summary>
    public class Builder
    {
        /// <summary>
        /// This is Contruct of the builder class.
        /// </summary>
        /// <param name="builder"></param>
        /// <param name="filePath"></param>
        /// <param name="delimiter"></param>
        /// <param name="header"></param>
        /// <returns>result.</returns>
        public int Construct1(ICSVFileBuilder builder, string filePath, string delimiter = ",", string header = "")
        {
           int result = builder.StateLoadData(filePath, delimiter, header);
           return result;
        }
    }
}
