//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=Builder.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder">builder.</param>
    /// <param name="filePath">filePath.</param>
    /// <param name="delimiter">delimiter.</param>
    /// <param name="header">header.</param>
    /// <returns>Int type.</returns>
    public delegate int DelegateCsvStateDataLoad(ICSVFileBuilder builder, string filePath, string delimiter = ",", string header = "");
    /// <summary>
    /// Builder class use like Directore of Project.
    /// </summary>
    public class Builder
    {
        /// <summary>
        /// This is Contruct of the builder class.
        /// </summary>
        /// <param name="builder"></param>
        /// <param name="filePath"></param>
        /// <param name="delimiter"></param>
        /// <param name="header"></param>
        /// <returns>result.</returns>
        public  static int Construct(ICSVFileBuilder builder, string filePath, string delimiter = ",", string header = "")
        {
           int result = builder.StateLoadData(filePath, delimiter, header);
           return result;
        }
    }
}
