//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=Factory.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System;

    /// <summary>
    /// Enum Containing Type of Exception mesaages.
    /// </summary>
    public enum CensusException
    {
        Wrong_File_Path,
        Wrong_Delimiter,
        Wrong_Header
    }

    /// <summary>
    /// Custom Exception class.
    /// </summary>
    public class CensusAnalyserException : Exception
    {
        public string Mgs;

        /// <summary>
        /// Initializes a new instance of the <see cref="CensusAnalyserException"/> class.
        /// </summary>
        /// <param name="message">.</param>
        public CensusAnalyserException(string message)
        {
            this.Mgs = message;
        }
    }
}
