//<auto-generated/>
/////------------------------------------------------------------------------
////<copyright file="ICSVFileBuilder.cs" company="BridgeLabz">
////author="Kuldeep"
////</copyright>
////-------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// ICSVFileBuilder is Interface.
    /// </summary>
    public interface ICSVFileBuilder
    {
        public int StateLoadData(string filePath, string delimiter = ",", string header = null);
    }
}
