//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=Factory.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System;

    /// <summary>
    /// This is main class of CensusAnalyserProblem Project.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// Main method of CensusAnalyserProblem Project.
        /// </summary>
        public static void Main()
        {
            string filePath = @"D:\BridgeLabz_CensusAnalyserProblem\StateCensusData.csv";
            Factory factory = new Factory();
            DelegateCsvStateDataLoad deleget=new DelegateCsvStateDataLoad(Builder.Construct);
            deleget(factory.GetObjectCSVStateCensus(),filePath);
        }
    }
}
