//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=Factory.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System;

    /// <summary>
    /// This is main class of CensusAnalyserProblem Project.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// Main method of CensusAnalyserProblem Project.
        /// </summary>
        public static void Main()
        {
            string path1 = @"D:\BridgeLabz_CensusAnalyserProblem\StateCensusData.csv";
            Builder builder = new Builder();
            Factory factory = new Factory();
            builder.Construct1(factory.GetObjectCSVStateCensus(), path1, ",", "AreaInSqKm");
            Console.WriteLine();
            string path2 = @"D:\BridgeLabz_CensusAnalyserProblem\StateCode.csv";
            builder.Construct1(factory.GetObjectCSVState(), path2, ",", "StateCode");
        }
    }
}
