//<auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=StateCensusAnalyser.cs" Company="Bridgelabz">
//   Copyright © 2020 Company="BridgeLabz"
// </copyright>
// <creator name="Kuldeep Kasaudhan"/>
// ----------------------------------------------------------------------------------------------------------------------
namespace CensusAnalyserProblem
{
    using System.IO;
    using System.Linq;

    /// <summary>
    /// StateCensusAnalyser class return file data.
    /// </summary>
    public class StateCensusAnalyser
    {
        /// <summary>
        /// CSVLoadData method return csv file.
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns>data.Length.</returns>
        public static int CSVLoadData(string filePath)
        {
            var line = File.ReadLines(filePath);
            string[] data = line.ToArray();
            return data.Length;
        }
    }
}
